#!/usr/bin/env bash
# ==============================================================================
# EC2 User Data – Task Management System bootstrap
#
# Runs as root on first boot of the Ubuntu 22.04 instance.
# Installs Docker, Docker Compose, fetches secrets from Secrets Manager,
# pulls the Docker image from ECR, and starts the application.
# ==============================================================================
set -euo pipefail

LOG_FILE="/var/log/userdata.log"
exec > >(tee -a "$LOG_FILE") 2>&1

echo "[$(date)] ▶ Starting Task Management System bootstrap"

# ── System Updates ─────────────────────────────────────────────────────────────
apt-get update -y
apt-get install -y --no-install-recommends \
  ca-certificates curl gnupg lsb-release \
  jq unzip python3-pip

# Install AWS CLI v2
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
unzip -q /tmp/awscliv2.zip -d /tmp/
/tmp/aws/install

# ── Docker Installation ────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
  echo "[$(date)] Installing Docker…"
  curl -fsSL https://get.docker.com -o /tmp/get-docker.sh
  bash /tmp/get-docker.sh
  usermod -aG docker ubuntu
fi

# ── Docker Compose (v2 plugin) ─────────────────────────────────────────────────
if ! docker compose version &>/dev/null; then
  echo "[$(date)] Installing Docker Compose plugin…"
  COMPOSE_VERSION=$(curl -fsSL --max-time 10 https://api.github.com/repos/docker/compose/releases/latest 2>/dev/null | jq -r .tag_name)
  if [ -z "$COMPOSE_VERSION" ] || [ "$COMPOSE_VERSION" = "null" ]; then
    COMPOSE_VERSION="v2.27.1"   # pinned fallback
    echo "[$(date)] Using fallback Docker Compose version: $COMPOSE_VERSION"
  fi
  mkdir -p /usr/local/lib/docker/cli-plugins
  curl -SL "https://github.com/docker/compose/releases/download/$${COMPOSE_VERSION}/docker-compose-linux-x86_64" \
    -o /usr/local/lib/docker/cli-plugins/docker-compose
  chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
fi

systemctl enable docker
systemctl start docker

# ── Fetch Secrets from AWS Secrets Manager ─────────────────────────────────────
echo "[$(date)] Fetching secrets from AWS Secrets Manager…"

DB_PASSWORD=$(aws secretsmanager get-secret-value \
  --secret-id "${db_password_secret_arn}" \
  --region    "${aws_region}" \
  --query     SecretString \
  --output    text | jq -r .password)

SECRET_KEY=$(aws secretsmanager get-secret-value \
  --secret-id "${app_secret_arn}" \
  --region    "${aws_region}" \
  --query     SecretString \
  --output    text)

JWT_SECRET_KEY=$(aws secretsmanager get-secret-value \
  --secret-id "${jwt_secret_arn}" \
  --region    "${aws_region}" \
  --query     SecretString \
  --output    text)

# ── Write Environment File ─────────────────────────────────────────────────────
# Write Environment File
APP_DIR="/home/ubuntu/taskmanager"
mkdir -p "$APP_DIR/env"

cat > "$APP_DIR/env/.env.prod" << EOF
# Your env vars here
EOF

# Fix permissions so ubuntu user can read it
chown -R ubuntu:ubuntu "$APP_DIR"
chmod 755 "$APP_DIR"
chmod 644 "$APP_DIR/env/.env.prod"


DATABASE_URL="postgresql://${db_username}:$${DB_PASSWORD}@${db_host}/${db_name}?sslmode=require"
REDIS_URL="redis://${redis_host}:${redis_port}/0"
CACHE_REDIS_URL="redis://${redis_host}:${redis_port}/1"

cat > "$APP_DIR/env/.env.prod" <<ENVEOF
# Auto-generated by Terraform user-data – do not edit manually
FLASK_ENV=production
FLASK_HOST=0.0.0.0
FLASK_PORT=${flask_port}
FLASK_DEBUG=false

DATABASE_URL=$${DATABASE_URL}
REDIS_URL=$${REDIS_URL}
CACHE_REDIS_URL=$${CACHE_REDIS_URL}
CACHE_TYPE=RedisCache
CACHE_DEFAULT_TIMEOUT=300

SECRET_KEY=$${SECRET_KEY}
JWT_SECRET_KEY=$${JWT_SECRET_KEY}
JWT_ACCESS_TOKEN_EXPIRES=3600

LOG_LEVEL=INFO
LOG_TO_STDOUT=true

RATELIMIT_ENABLED=true
ENVEOF

chmod 600 "$APP_DIR/env/.env.prod"

# ── Authenticate Docker with ECR ───────────────────────────────────────────────
echo "[$(date)] Authenticating with ECR…"
aws ecr get-login-password --region "${aws_region}" | \
  docker login --username AWS --password-stdin "${ecr_repo_url}"

# ── Environment-specific Docker Compose Files ─────────────────────────────────
ENVIRONMENT="${environment}"

if [ "$ENVIRONMENT" = "prod" ]; then
  COMPOSE_FILE="$APP_DIR/docker-compose.prod.yml"

  cat > "$COMPOSE_FILE" <<DCEOF
version: '3.8'

services:
  app:
    image: ${ecr_repo_url}:latest
    container_name: taskmanager_app
    restart: unless-stopped
    env_file:
      - /home/ubuntu/taskmanager/env/.env.prod
    ports:
      - "${flask_port}:${flask_port}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${flask_port}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"
DCEOF

else
  COMPOSE_FILE="$APP_DIR/docker-compose.dev.yml"

  # On EC2, both dev and prod deployments use the same secrets file (.env.prod)
  # written from AWS Secrets Manager. The dev distinction is the runtime command:
  # python app.py (with hot-reload support) instead of gunicorn.
  cat > "$COMPOSE_FILE" <<DCEOF
version: '3.8'

services:
  app:
    image: ${ecr_repo_url}:latest
    container_name: taskmanager_app
    command: python app.py
    restart: unless-stopped
    env_file:
      - /home/ubuntu/taskmanager/env/.env.prod
    ports:
      - "${flask_port}:${flask_port}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${flask_port}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: json-file
      options:
        max-size: "50m"
        max-file: "3"
DCEOF

fi

echo "[$(date)] Created compose file: $COMPOSE_FILE (environment: $ENVIRONMENT)"

# ── Pull and Start Container ───────────────────────────────────────────────────
echo "[$(date)] Pulling Docker image from ECR…"
if ! docker pull "${ecr_repo_url}:latest"; then
  echo "[$(date)] ⚠️  Image pull failed – no image available yet."
  echo "[$(date)] Bootstrap complete. Push an image to ECR to start the app."
  echo "[$(date)] Run: terraform output ecr_push_commands"
  exit 0
fi

echo "[$(date)] Starting application containers…"
docker compose -f "$COMPOSE_FILE" up -d --remove-orphans

# ── Database Migrations ────────────────────────────────────────────────────────
echo "[$(date)] Waiting for application to be ready before running migrations…"
HEALTH_URL="http://localhost:${flask_port}/health"
MAX_WAIT=120
WAITED=0
until curl -sf "$HEALTH_URL" >/dev/null 2>&1 || [ "$WAITED" -ge "$MAX_WAIT" ]; do
  sleep 5
  WAITED=$((WAITED + 5))
  echo "[$(date)] Still waiting for app (${WAITED}s)…"
done

if curl -sf "$HEALTH_URL" >/dev/null 2>&1; then
  echo "[$(date)] App is healthy. Running database migrations…"
  MIGRATION_MSG="Auto migration $(date +%Y%m%d%H%M%S)"
  if docker compose -f "$COMPOSE_FILE" exec -T app flask db migrate -m "$MIGRATION_MSG" 2>&1; then
    echo "[$(date)] Migration script created successfully."
  else
    echo "[$(date)] Migration script step skipped (no changes detected or already exists)."
  fi

  if docker compose -f "$COMPOSE_FILE" exec -T app flask db upgrade 2>&1; then
    echo "[$(date)] Database upgrade applied successfully."
  else
    echo "[$(date)] ⚠️  Database upgrade failed – check logs for details."
  fi
else
  echo "[$(date)] ⚠️  App did not become healthy within ${MAX_WAIT}s – skipping migrations."
fi

# ── Install systemd service for auto-restart on reboot ────────────────────────
# Note: $COMPOSE_FILE is expanded by bash when writing the heredoc (unquoted delimiter),
# so the systemd unit file contains the literal resolved path.
cat > /etc/systemd/system/taskmanager.service <<SERVICEEOF
[Unit]
Description=Task Management System
Requires=docker.service
After=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=/home/ubuntu/taskmanager
ExecStart=/usr/bin/docker compose -f $COMPOSE_FILE up -d --remove-orphans
ExecStop=/usr/bin/docker compose -f $COMPOSE_FILE down
User=ubuntu

[Install]
WantedBy=multi-user.target
SERVICEEOF

systemctl daemon-reload
systemctl enable taskmanager.service

echo "[$(date)] ✅ Bootstrap complete. App running at http://$(curl -s http://169.254.169.254/latest/meta-data/public-ipv4):${flask_port}"
